### ISSUE TITLE
Teammitglieder

### ISSUE THREAD

**Issue by saerdnaer** [codeformunich/mietpreise#1]
Jeder der Lust hat bei dem Projekt mitzumachen bitte hier kommentieren, auf welchen Themenbereich er Lust hat.

**Comment by mattfullerton** [comment]
Datenbank und Schnittstellen Frontend <--> DB
Analytics auf den Daten

**Comment by MarHai** [comment]
question formulation, wording, data analytics

**Comment by saerdnaer** [comment]
geo data and openstreetmap support

**Comment by gefei** [comment]
Backend und Javascript-Teil vom Frontend

**Comment by konstin** [comment]
UI-Design und Formulierungen

**Comment by saerdnaer** [comment]
more information in https://pad.okfn.org/p/oklab-muc-housing-02
